---
title: "coxph"
author: "min"
date: "2023-12-02"
output: html_document
---

```{r}
library(tidyverse)
library(survival)
library(survminer)
library(riskRegression)
library(regclass)
```

```{r}
aids = read_csv("data/AIDS_Clinical_Trials_Group175.csv") %>% mutate(trt = as.factor(trt),
                                                                     hemo = as.factor(hemo),
                                                                     homo = as.factor(homo),
                                                                     drugs = as.factor(drugs),
                                                                     race = as.factor(race),
                                                                     gender = as.factor(gender),
                                                                     str2 = as.factor(str2),
                                                                     symptom = as.factor(symptom)) %>% select(time, cid, trt, age, wtkg, hemo, homo, drugs, karnof, race, gender, str2, symptom, cd40, cd80) %>% arrange(time) %>% drop_na()
```

#### model selection

*selection on personal information*
```{r}
selectCox(Surv(time, cid) ~ trt + age + wtkg + homo + race + gender, data = aids, rule = "aic")
```
$In
[1] "trt" "age"

*selection on medical history/treatment history/lab results*
```{r}
selectCox(Surv(time, cid) ~ trt + hemo + drugs + karnof + str2 + symptom + cd40 + cd80, data = aids, rule = "aic")
```
$In
[1] "trt"     "drugs"   "karnof"  "str2"    "symptom" "cd40"    "cd80"  

*selection with interaction*
```{r}
selectCox(Surv(time, cid) ~ trt + drugs + karnof + str2 + symptom + cd40 + cd80 + age + age * drugs + age * trt, data = aids, rule = "aic")
```
$In
[1] "trt"         "karnof"      "str2"        "symptom"     "cd40"        "cd80"        "drugs * age"

*final model*
```{r}
cox1 = coxph(Surv(time, cid) ~ trt + karnof + str2 + symptom + cd40 + cd80 + age * drugs, data = aids)
```

```{r}
summary(cox1)
```

*final model with age_group*
```{r}
aids = aids %>% mutate(age_group = as.factor(ifelse(age >= 11 & age <= 30, "11-30", ifelse(age >= 31 & age <= 50, "31-50", "51-70"))))
```

```{r}
cox2 = coxph(Surv(time, cid) ~ trt + age_group + drugs + karnof + str2 + symptom + cd40 + cd80 + age_group * drugs, data = aids)
```

```{r}
summary(cox2)
```

#### model checking

*check multicollinearity*
```{r}
VIF(cox2)
```

*Plot log-log survival curve*
```{r}
par(mfrow = c(2,4))
var_list = names(aids)

for (i in var_list) {
plot(survfit(Surv(time, cid) ~ aids[[i]], data = aids),
fun = 'cloglog',
conf.int = FALSE,
col = 1,
lty = 1,
xlab = "Time",
ylab = "Log-log of S(t)",
main = "Log-Log Survival Curves")
}
```

*Plot the observed and fitted*
```{r}
par(mfrow = c(1,1))

plot(survfit(Surv(time, cid) ~ 1, data = aids),
conf.int = FALSE,
col = 1,
lty = 1,
ylim = c(0.55,1),
xlab = "Time",
ylab = "Survival Probability",
main = "Observed vs Fitted Survival Curves")

lines(survfit(cox2),
conf.int = FALSE,
col = 2,
lty = 2,
ylim = c(0.55,1))

legend("bottomleft",
legend = c("KM", "Cox"),
col = 1:2,
lty = c(1, 2),
cex = 0.5,
merge = TRUE)
```